on: 
  #push:
  #  branches:
   #   - main
  workflow_dispatch:
  
name: Deploy Web (.NET)

env:
  VERSION_NAME: WebProd
  WEBAPP_PACKAGE_PATH: ./publish
  SERVER_PATH: "./conectaesporte.com/"
  SOLUTION_APP: .\ConectaEsporteSolution\ConectaEsporteSolution.sln
  PROJECT_APP: .\ConectaEsporteSolution\ConectaEsporte.Web\ConectaEsporte.Web.csproj
  PROJECT_RELEASE: "./ConectaEsporteSolution/ConectaEsporte.Web/bin/Release/"
jobs:
  web-deploy:
    name: Deploy
    runs-on: windows-latest
    steps:
      - name: 1 🚚 Get latest code
        uses: actions/checkout@v2
      - name: 2 🚚 Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
      - name: 3 🚚 Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
      - name: 4 🚚 Setup Chrome
        uses: browser-actions/setup-chrome@v0.0.0
      - name: 5 🚚 Restore NuGet packages
        run: nuget restore ${{ env.SOLUTION_APP }}
 
      - name: 6 🚚 Construir e empacotar aplicacao
        run: msbuild ${{ env.SOLUTION_APP }} '/p:Configuration=Release' -t:rebuild 
      
      - name: 7 🚚 Publish app for deploy
        # run: dotnet publish ${{ env.PROJECT_APP }} --no-build --output ${{ env.WEBAPP_PACKAGE_PATH }}
        run: dotnet publish ${{ env.PROJECT_APP }} --no-build --output ${{ env.PROJECT_RELEASE }}
    #  - name: Move ZIP to S3Bucket
    #    run: |
    #      aws s3 cp package.zip s3://esteiradigitalfront/EsteiraDigital/${{ env.VERSION_NAME }}.zip

        
      - name: 8 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }} 
          username: ${{ secrets.FTP_USER }} 
          password: ${{ secrets.FTP_PASSWORD }} 
          local-dir: ${{ env.PROJECT_RELEASE }}
          #package: ${{ env.WEBAPP_PACKAGE_PATH }}
          server-dir: ${{ env.SERVER_PATH }}
          #delete: true
